## EJERCICIOS DIAGONALIZACIÓN

In [1]:
import numpy as np
import numpy.linalg as LA

**Pregunta 1**

In [2]:
A = np.array([[1, 0, 0, 1], [2, -1, 0, -1], \
              [0, -1,  2, 0], [-1, 0, 0, -2]])

In [3]:
l, w = LA.eig(A)

In [4]:
print(l, '\n', ' = '*20, '\n', w)

[ 2.         -1.          0.61803399 -1.61803399] 
  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  
 [[ 0.          0.          0.47416084 -0.12131049]
 [ 0.          0.9486833   0.69802921  0.90644846]
 [ 1.          0.31622777  0.50509868  0.25053619]
 [ 0.          0.         -0.18111332  0.31759498]]


Como podemos observar las multiplicidades algebraicas son iguales a 1 para cada uno de los valores propios, así como las geometricas (todos tienen un dimension uno en sus subespacio)

**Pregunta 2**

In [5]:
A = np.array([[0, -1], [1, 0]])

In [6]:
l, w = LA.eig(A)

In [7]:
print(l, '\n', ' = '*20, '\n', w)

[0.+1.j 0.-1.j] 
  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  
 [[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]


In [8]:
B = np.array([[2, -4, -4],[0, -2, 0], [-4, 4, 2]])

In [9]:
l, w = LA.eig(B)

In [10]:
print(l, '\n', ' = '*20, '\n', w)

[ 6. -2. -2.] 
  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  
 [[ 0.70710678  0.70710678  0.40824829]
 [ 0.          0.          0.81649658]
 [-0.70710678  0.70710678 -0.40824829]]


En este caso observamos multiplicidades algebraicas n = 1 para l = 6, y n = 2, para l = -2, en caso de las geométricas sucede igual

In [11]:
D = np.array([[2, -1, 3, -3], [0, -1, 0, 0], [-1, 3, 1, 0], [-1, 2, 2, 0]])

In [12]:
l, w = LA.eig(D)

In [13]:
print(l, '\n', ' = '*20, '\n', w)

[ 2.67169988+0.j          0.16415006+1.04686932j  0.16415006-1.04686932j
 -1.        +0.j        ] 
  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  
 [[-0.70122829+0.j          0.58673072-0.12760922j  0.58673072+0.12760922j
   0.77919372+0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        -0.j
   0.41251432+0.j        ]
 [ 0.4194702 +0.j          0.3477186 +0.28283392j  0.3477186 -0.28283392j
  -0.22917462+0.j        ]
 [ 0.57647519+0.j          0.6622384 +0.j          0.6622384 -0.j
   0.41251432+0.j        ]]


**Pregunta 3**

In [14]:
A = np.array([[1, 4], [0, 3]])

In [15]:
l, w = LA.eig(A)

In [16]:
print(l, '\n', ' = '*20, '\n', w)

[1. 3.] 
  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  
 [[1.         0.89442719]
 [0.         0.4472136 ]]


In [17]:
D = LA.linalg.matmul(LA.inv(w),A)
D = LA.linalg.matmul(D, w)
print(D)

[[1. 0.]
 [0. 3.]]


In [18]:
B = np.array([[1, 2, 0], [2, -1, 5], [0, 5, 1]])

In [19]:
l, w = LA.eig(B)

In [20]:
print(l, '\n', ' = '*20, '\n', w)

[-5.47722558  1.          5.47722558] 
  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  
 [[ 2.37432504e-01  9.28476691e-01  2.85581583e-01]
 [-7.68951944e-01  2.37389501e-16  6.39306583e-01]
 [ 5.93581261e-01 -3.71390676e-01  7.13953957e-01]]


In [21]:
D = LA.linalg.matmul(LA.inv(w),B)
D = LA.linalg.matmul(D, w)
print(D)

[[-5.47722558e+00  8.88178420e-16 -1.77635684e-15]
 [ 9.15933995e-16  1.00000000e+00  1.66533454e-16]
 [-2.22044605e-15  1.11022302e-15  5.47722558e+00]]


In [22]:
C = np.array([[1, 1, 3], [0, 2, 0], [-2, 0, 3]])

In [23]:
l, w = LA.eig(C)

In [24]:
print(l, '\n', ' = '*20, '\n', w)

[2.+2.23606798j 2.-2.23606798j 2.+0.j        ] 
  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  
 [[ 0.77459667+0.j          0.77459667-0.j         -0.18257419+0.j        ]
 [ 0.        +0.j          0.        -0.j          0.91287093+0.j        ]
 [ 0.25819889+0.57735027j  0.25819889-0.57735027j -0.36514837+0.j        ]]


**Pregunta 4**

In [25]:
A = np.array([[1, 0, 0, 1], [2, -1, 0, -1],[0, -1, 2, 0], [-1, 0, 0, 2]])

In [26]:
l, w = LA.eig(A)

In [27]:
print(l, '\n', ' = '*20, '\n', w)

[ 2. +0.j        -1. +0.j         1.5+0.8660254j  1.5-0.8660254j] 
  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  
 [[ 0.        +0.j          0.        +0.j          0.29580399-0.51234754j
   0.29580399+0.51234754j]
 [ 0.        +0.j          0.9486833 +0.j         -0.12677314-0.36596253j
  -0.12677314+0.36596253j]
 [ 1.        +0.j          0.31622777+0.j          0.25354628-0.29277002j
   0.25354628+0.29277002j]
 [ 0.        +0.j          0.        +0.j          0.59160798+0.j
   0.59160798-0.j        ]]


In [28]:
D = LA.linalg.matmul(LA.inv(w),A)
D = LA.linalg.matmul(D, w)
print(D)

[[ 2.00000000e+00+0.00000000e+00j -1.11022302e-16+0.00000000e+00j
  -6.98587048e-17+1.47968247e-16j -1.77168684e-17-7.40763575e-17j]
 [ 0.00000000e+00+0.00000000e+00j -1.00000000e+00+0.00000000e+00j
  -3.10089649e-16+2.68546017e-16j -2.95099925e-16-1.90657126e-16j]
 [ 0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   1.50000000e+00+8.66025404e-01j -1.11022302e-16+2.22044605e-16j]
 [ 0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
  -3.33066907e-16-3.33066907e-16j  1.50000000e+00-8.66025404e-01j]]


**Pregunta 5**

In [29]:
A = np.array([[1, -1, -1], [-1, 1, -1], [-1, -1, 1]])

In [30]:
l, w = LA.eig(A)

In [31]:
print(l, '\n', ' = '*20, '\n', w)

[-1.  2.  2.] 
  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  
 [[ 0.57735027 -0.81649658  0.42755853]
 [ 0.57735027  0.40824829 -0.81618716]
 [ 0.57735027  0.40824829  0.38862863]]


In [32]:
D = LA.linalg.matmul(LA.inv(w),A)
D = LA.linalg.matmul(D, w)
print(D)

[[-1.00000000e+00  5.55111512e-16 -4.44089210e-16]
 [-3.33066907e-16  2.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  1.11022302e-16  2.00000000e+00]]


**Pregunta 6**

In [33]:
A = np.array([[0, 0, 4], [1, 2, 1], [2, 4, -2]])

In [34]:
l, w = LA.eig(A)

In [35]:
print(l, '\n', ' = '*20, '\n', w)

[ 4.00000000e+00  3.81639165e-17 -4.00000000e+00] 
  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  
 [[-5.77350269e-01 -8.94427191e-01 -7.07106781e-01]
 [-5.77350269e-01  4.47213595e-01  4.19624860e-16]
 [-5.77350269e-01  0.00000000e+00  7.07106781e-01]]


In [36]:
D = LA.linalg.matmul(LA.inv(w),A)
D = LA.linalg.matmul(D, w)
print(np.floor(D)) # LOS -1 son 0 en realidad

[[ 4.  0. -1.]
 [-1.  0.  0.]
 [-1. -1. -4.]]


**Pregunta 7**

In [37]:
A = np.array([[3, -1 ,1], [0,2, 0], [1, -1, 3]])

In [38]:
A

array([[ 3, -1,  1],
       [ 0,  2,  0],
       [ 1, -1,  3]])

In [39]:
l, w = LA.eig(A)

In [40]:
print(l, '\n', ' = '*20, '\n', w)

[4. 2. 2.] 
  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  
 [[ 0.70710678 -0.70710678  0.40824829]
 [ 0.          0.          0.81649658]
 [ 0.70710678  0.70710678  0.40824829]]


**Pregunta 8**

In [41]:
A = np.array([[1, -4, 0], [0, 4, 0], [0, 0, 3]])

In [42]:
l, w = LA.linalg.eig(A)

In [43]:
print(l, '\n', ' = '*20, '\n', w)

[1. 4. 3.] 
  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  
 [[ 1.  -0.8  0. ]
 [ 0.   0.6  0. ]
 [ 0.   0.   1. ]]


**Pregunta 12**

In [44]:
A = np.array([[0, 1], [-1, 1]])

In [45]:
l, w = LA.eig(A)

In [46]:
print(l, '\n', ' = '*20, '\n', w)

[0.5+0.8660254j 0.5-0.8660254j] 
  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  
 [[0.70710678+0.j         0.70710678-0.j        ]
 [0.35355339+0.61237244j 0.35355339-0.61237244j]]


In [47]:
D = LA.linalg.matmul(LA.inv(w),A)
D = LA.linalg.matmul(D, w)
print(D)

[[5.00000000e-01+8.66025404e-01j 1.94289029e-16+1.66533454e-16j]
 [1.94289029e-16-1.66533454e-16j 5.00000000e-01-8.66025404e-01j]]


In [48]:
B = np.array([[4, -2, -2], [0, -2, 0], [-2, 2, 4]])

In [49]:
l, w = LA.eig(B)

In [50]:
print(l, '\n', ' = '*20, '\n', w)

[ 6.  2. -2.] 
  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  
 [[ 0.70710678  0.70710678  0.23570226]
 [ 0.          0.          0.94280904]
 [-0.70710678  0.70710678 -0.23570226]]


In [51]:
C = np.array([[-3, 5, 5], [0, -2, 0], [-2, 2, 4]])

In [52]:
l, w = LA.eig(C)

In [53]:
print(l, '\n', ' = '*20, '\n', w)

[-1.  2. -2.] 
  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  
 [[-0.92847669 -0.70710678 -0.91287093]
 [ 0.          0.          0.18257419]
 [-0.37139068 -0.70710678 -0.36514837]]


In [54]:
D = np.array([[1, 1, 1, 1],[1, 1, -1, -1],[1, -1, 1, -1], [1, -1, -1, 1]])

In [55]:
l, w = LA.eig(D)

In [56]:
print(l, '\n', ' = '*20, '\n', w)

[ 2. -2.  2.  2.] 
  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  
 [[ 0.8660254   0.5         0.2085966  -0.04421078]
 [ 0.28867513 -0.5         0.86198968  0.18303437]
 [ 0.28867513 -0.5        -0.32669654 -0.79872244]
 [ 0.28867513 -0.5        -0.32669654  0.57147729]]


**Pregunta 13**

In [57]:
A = np.array([[4,1],[0,-3]])

In [58]:
l, w = LA.eig(A)

In [59]:
print(l, '\n', ' = '*20, '\n', w)

[ 4. -3.] 
  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  
 [[ 1.         -0.14142136]
 [ 0.          0.98994949]]


In [60]:
D = LA.linalg.matmul(LA.inv(w),A)
D = LA.linalg.matmul(D, w)
print(D)

[[ 4.  0.]
 [ 0. -3.]]


In [71]:
B = np.array([[-1, -2, 1], [0, 2, 0], [-1, 13, -3]])

In [72]:
l, w = LA.eig(B)

In [73]:
print(l, '\n', ' = '*20, '\n', w)

[-1.99999998 -2.00000002  2.        ] 
  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  =  
 [[ 0.70710679 -0.70710677  0.06800641]
 [ 0.          0.          0.36270084]
 [-0.70710677  0.70710679  0.92942091]]
