# DIAGONALIZACIÓN CON PYTHON

In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
A = np.array([[2, -2, 1], [2, -8, -2], [1, 2, 2]])

In [3]:
print(A)

[[ 2 -2  1]
 [ 2 -8 -2]
 [ 1  2  2]]


In [5]:
w, v = LA.eig(A)

In [6]:
l1 = w[0]

In [7]:
v1 = v[:, 0]

In [8]:
print(np.dot(A, v1))

[-1.64991582 -6.59966329  1.64991582]


In [9]:
print(l1*v1)

[-1.64991582 -6.59966329  1.64991582]


In [10]:
np.dot(A, v1) == l1*v1

array([ True, False,  True])

In [13]:
np.floor(np.dot(A, v1)) == np.floor(l1 * v1)

array([ True,  True,  True])

In [15]:
np.isclose(np.dot(A, v1), l1*v1)

array([ True,  True,  True])