# Factorización LU con Python

**Para hacer factorizaciones LU utilizaremos la librería scipy**

In [3]:
import numpy as np
import scipy
import scipy.linalg

In [10]:
A = scipy.array([[1, 3, 0, -1], [2, 1, -1, 5], [0, -2, 3, -1], [1,1,3,1]])

In [11]:
A

array([[ 1,  3,  0, -1],
       [ 2,  1, -1,  5],
       [ 0, -2,  3, -1],
       [ 1,  1,  3,  1]])

In [12]:
P, L, U = scipy.linalg.lu(A)

In [13]:
P # Matriz de permutación o cambio de filas

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
L # Lower triangle matrix

array([[ 1. ,  0. ,  0. ,  0. ],
       [ 0.5,  1. ,  0. ,  0. ],
       [ 0. , -0.8,  1. ,  0. ],
       [ 0.5,  0.2,  1. ,  1. ]])

In [15]:
U # Upper triangle matrix

array([[ 2. ,  1. , -1. ,  5. ],
       [ 0. ,  2.5,  0.5, -3.5],
       [ 0. ,  0. ,  3.4, -3.8],
       [ 0. ,  0. ,  0. ,  3. ]])

In [16]:
B = scipy.array([[0, 1, 3], [1, 3, -2], [-3, -2, 1]])

In [17]:
B

array([[ 0,  1,  3],
       [ 1,  3, -2],
       [-3, -2,  1]])

In [23]:
P2, L2, U2 = scipy.linalg.lu(B)

In [24]:
P2

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [25]:
L2

array([[ 1.        ,  0.        ,  0.        ],
       [-0.33333333,  1.        ,  0.        ],
       [-0.        ,  0.42857143,  1.        ]])

In [26]:
U2

array([[-3.        , -2.        ,  1.        ],
       [ 0.        ,  2.33333333, -1.66666667],
       [ 0.        ,  0.        ,  3.71428571]])

**Reduciendo información de la factorización LU**

In [28]:
B

array([[ 0,  1,  3],
       [ 1,  3, -2],
       [-3, -2,  1]])

In [30]:
LU, piv = scipy.linalg.lu_factor(B)

In [33]:
LU # Concentrar la Lower y Upper

array([[-3.        , -2.        ,  1.        ],
       [-0.33333333,  2.33333333, -1.66666667],
       [-0.        ,  0.42857143,  3.71428571]])

In [35]:
piv #La primera fila ha sido intercambiada por la última

array([2, 1, 2], dtype=int32)

**Solución de sistemas lineales con Factorización LU**

In [36]:
A = scipy.array([[0,1,3],[1,3,-2],[-3,-2,-1]])
LU, piv = scipy.linalg.lu_factor(A)
b = [1, 3, -2]
x = scipy.linalg.lu_solve((LU, piv), b)
x

array([-0.00000000e+00,  1.00000000e+00, -1.98254112e-18])

In [37]:
for i, x in enumerate(x):
    print('x',i , ' = ', x)

x 0  =  -0.0
x 1  =  1.0
x 2  =  -1.9825411154020644e-18


In [4]:
A1 = scipy.array([[0, 2, -3, 4], [0, 0, -5, -1], [5, -1, -2, 0], [-2, 0, 4, 6]])
A2 = scipy.array([[1, 2, -1, 4], [0, -1, 5, 8], [2, 3, 1, 4], [1, -1, 6, 4]])
A3 = scipy.array([[2, 4 , -2, 0], [3, 7, 5, -4], [-1, 2, -2, 5], [6, 1, 0, 2]])
A4 = scipy.array([[0, 2, 3, 1], [0, 4, -1, 5], [2, 0, 3, 1], [1, -4, 5, 6]])

In [5]:
P1, L1, U1 = scipy.linalg.lu(A1)

In [6]:
P1

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [7]:
L1

array([[ 1.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ],
       [-0.4 , -0.2 , -0.52,  1.  ]])

In [8]:
U1

array([[ 5.  , -1.  , -2.  ,  0.  ],
       [ 0.  ,  2.  , -3.  ,  4.  ],
       [ 0.  ,  0.  , -5.  , -1.  ],
       [ 0.  ,  0.  ,  0.  ,  6.28]])

In [9]:
P2, L2, U2 = scipy.linalg.lu(A2)

In [10]:
P2

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [11]:
L2

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.5       ,  1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.4       ,  1.        ,  0.        ],
       [ 0.5       , -0.2       , -0.14285714,  1.        ]])

In [12]:
U2

array([[ 2.        ,  3.        ,  1.        ,  4.        ],
       [ 0.        , -2.5       ,  5.5       ,  2.        ],
       [ 0.        ,  0.        ,  2.8       ,  7.2       ],
       [ 0.        ,  0.        ,  0.        ,  3.42857143]])

In [13]:
P3, L3, U3 = scipy.linalg.lu(A3)

In [14]:
P3

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]])

In [15]:
L3

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.5       ,  1.        ,  0.        ,  0.        ],
       [ 0.33333333,  0.56410256,  1.        ,  0.        ],
       [-0.16666667,  0.33333333,  0.7606383 ,  1.        ]])

In [16]:
U3

array([[ 6.        ,  1.        ,  0.        ,  2.        ],
       [ 0.        ,  6.5       ,  5.        , -5.        ],
       [ 0.        ,  0.        , -4.82051282,  2.15384615],
       [ 0.        ,  0.        ,  0.        ,  5.36170213]])

In [17]:
P4, L4, U4 = scipy.linalg.lu(A4)

In [18]:
P4

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [19]:
L4

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.5       ,  1.        ,  0.        ],
       [ 0.5       , -1.        ,  0.71428571,  1.        ]])

In [20]:
U4

array([[ 2.        ,  0.        ,  3.        ,  1.        ],
       [ 0.        ,  4.        , -1.        ,  5.        ],
       [ 0.        ,  0.        ,  3.5       , -1.5       ],
       [ 0.        ,  0.        ,  0.        , 11.57142857]])

In [22]:
A = np.array([[1, 2, 3, 4], [0, 1, 0, 1], [4, 3, 2, 1], [3, 3, 0, 5]])
int(np.linalg.det(A))

-49

In [24]:
A = np.array([[1, 1, 1, -1], [0, 1, 3, 1], [-1, 0, 2, 1], [0, 3, 0, 5]])
int(np.linalg.det(A))

-9

In [25]:
C = np.array([[1, 1, 1, -1, 0], [0, 1, 3, 1, 0], [-1, 0, 2, 1, 0], [0, 3, 0, 5, 0], [1, 2, 3, 4, 5]])

In [27]:
C

array([[ 1,  1,  1, -1,  0],
       [ 0,  1,  3,  1,  0],
       [-1,  0,  2,  1,  0],
       [ 0,  3,  0,  5,  0],
       [ 1,  2,  3,  4,  5]])

In [28]:
int(np.linalg.det(C))

-45

In [29]:
D = np.array([[0, 0, 0, 2], [0, 5, 0, 3], [1, 2, 3, -2], [4, 0, -3, 0]])

In [30]:
D

array([[ 0,  0,  0,  2],
       [ 0,  5,  0,  3],
       [ 1,  2,  3, -2],
       [ 4,  0, -3,  0]])

In [31]:
int(np.linalg.det(D))

-149

In [33]:
A = np.array([[1, 1, 1], [2,1, 2], [0, 2, 5]])
np.linalg.det(A)

-4.999999999999999

In [34]:
B = np.array([[3, 1, 5], [2, 1,2], [1, -2 , 3]])

In [35]:
np.linalg.det(B)

-7.999999999999998

In [36]:
np.linalg.solve(B, np.array([2, 0, 1]))

array([-1.375,  0.5  ,  1.125])

In [37]:
C = np.array([[3, 0, -7], [2, 1, 2], [-2, 2, 3]])

In [38]:
np.linalg.det(C)

-44.99999999999999

In [39]:
D = np.array([[3, -3, -7, 1], [2, 0, 2, 2], [-2, 2, 3, -1], [2, 2, 3, 1]])

In [40]:
np.linalg.det(D)

12.000000000000005

In [43]:
np.linalg.solve(C, np.array([2, 9, -11]))

array([ 4.55555556, -3.44444444,  1.66666667])

In [52]:
C = np.array([[1, 2, 3, 4], [4, 3, -2, -1],[1, -2, -3, 4], [0, 0, 4, 0]])

In [66]:
print(C)
np.linalg.det(C)

[[ 1  2  3  4]
 [ 4  3 -2 -1]
 [ 1 -2 -3  4]
 [ 0  0  4  0]]


272.0000000000001

In [73]:
C1 = np.linalg.inv(C)
for row in (np.linalg.inv(C)):
    print(row)

[-0.14705882  0.23529412  0.20588235  0.38235294]
[ 2.50000000e-01 -9.46212805e-18 -2.50000000e-01 -3.75000000e-01]
[0.   0.   0.   0.25]
[ 0.16176471 -0.05882353  0.07352941 -0.09558824]


In [75]:
for row  in (C * C1):
    print(row)

[-0.14705882  0.47058824  0.61764706  1.52941176]
[ 1.00000000e+00 -2.83863842e-17  5.00000000e-01  3.75000000e-01]
[ 0. -0. -0.  1.]
[ 0.         -0.          0.29411765 -0.        ]


In [93]:
A = np.array([[1, 1, 1], [0, -1, -1], [-1, 0, 1]])
AT = A.T
np.linalg.det(AT)

-1.0

In [105]:
2/7

0.2857142857142857