# MATRICES CON PYTHON

Utilizaremos la libreria numpy

## Creación de matrices

In [15]:
import numpy as np
# EMPEZAMOS CON LAS LISTAS DE PYTHON
row = [1, 2, 3] #Para crear un vector fila
row

[1, 2, 3]

In [16]:
col = [[1], [2], [3]] #Para crear un vector columna
col

[[1], [2], [3]]

In [17]:
M = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] #Para crear una matriz
M

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
M[0][0] # Elemento a11

1

In [19]:
M[0] # para llamar una fila

[1, 2, 3]

In [20]:
M = np.array(M)
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
M = np.array(M, dtype = complex)
print(M)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]
 [7.+0.j 8.+0.j 9.+0.j]]


In [22]:
M = np.array(M, dtype = float)
print(M)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


/home/guillem/anaconda3/envs/masterds/lib/python3.7/site-packages/ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


In [24]:
M[1] # Para llamar la segunda fila

array([4., 5., 6.])

In [26]:
M[:, 0] # Para llamar la primera columna

array([1., 4., 7.])

In [29]:
# Para crear un matriz nula np.zeros((fil, col))
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
# Para crear una matriz de unos
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
# Para crear una matriz diagonal
x = [1, 2, 3, 4]
N = np.diag(x)
print(N)
# Si utilizamos np.diag con una matriz obtenemos su diagonal
print('=' * 50)
print(np.diag(M))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[1. 5. 9.]


In [35]:
#Para saber la dimensión de una matriz
np.shape(M)

(3, 3)

## Manipulación de matrices con Python

In [37]:
# Suma todos los elementos de una matriz
np.sum(M)

45.0

In [39]:
# Suma por filas y columnas
print(np.sum(M, axis = 0)) # por filas
print('=' * 50)
print(np.sum(M, axis = 1)) # por columnas

[12. 15. 18.]
[ 6. 15. 24.]


In [40]:
# Calcular el productorio
np.prod(M)

362880.0

In [41]:
# Calcular la media
np.mean(M)

5.0

In [43]:
# Calcula la media por filas y columnas
print(np.mean(M, axis = 0)) # Por filas
print('='*50)
print(np.mean(M, axis = 1)) # Por columnas

[4. 5. 6.]
[2. 5. 8.]


## Operaciones con matrices

In [46]:
# Para calcular la transpuesta

print(M.transpose())
print('=' * 50)
print(M.T)

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [47]:
# Para calcular la traza de una matriz
print(M.trace())

15.0


In [48]:
# Suma de matrices
A = np.array([[1, 2], [2, 0]])
B = np.array([[3, 0], [1, 4]])
print(A + B)
A + B == B + A # Se cumple la propiedad conmutativa

[[4 2]
 [3 4]]


array([[ True,  True],
       [ True,  True]])

In [49]:
# Producto de matrices por escalar
print(5 * A)

[[ 5 10]
 [10  0]]


In [51]:
# Producto de matrices
print(A.dot(B))
A.dot(B) == B.dot(A) #No se cumple la propiedad conmutativa

[[5 8]
 [6 0]]


array([[False, False],
       [False, False]])

In [52]:
print(A * B) # Esto es un producto tensorial

[[3 0]
 [2 0]]


In [54]:
# Para calcular la potencia de una matriz
print(np.linalg.matrix_power(A, 5))

[[65 58]
 [58 36]]


In [56]:
# Para caluclar el rango de una matriz
np.linalg.matrix_rank(A)

2

In [57]:
# Calculo de inversas
print(np.linalg.inv(A))

[[ 0.    0.5 ]
 [ 0.5  -0.25]]


In [58]:
# Comprobamos que la inversa es correcta
np.linalg.inv(A).dot(A) # Debe ser igual a la identidad

array([[1., 0.],
       [0., 1.]])